import Loading from "@/components/Loading";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import NavContext from "../context/NavContext";
import FullScreenNavbar from "@/components/Navigation/FullScreenNavbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Loading>
          <NavContext>
            <Navbar />
            <FullScreenNavbar/>
            {children}
          </NavContext>
        </Loading>
      </body>
    </html>
  );
}
