import Loading from "@/components/Loading";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Loading>
          {children}
        </Loading>
      </body>
    </html>
  );
}
